import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val databinding_adapters: String = "androidx.databinding:databinding-adapters:_"

    public const val databinding_common: String = "androidx.databinding:databinding-common:_"

    public const val databinding_compiler: String = "androidx.databinding:databinding-compiler:_"

    public const val databinding_ktx: String = "androidx.databinding:databinding-ktx:_"

    public const val databinding_runtime: String = "androidx.databinding:databinding-runtime:_"

    public const val viewbinding: String = "androidx.databinding:viewbinding:_"

    public const val navigation_fragment_ktx: String =
            "androidx.navigation:navigation-fragment-ktx:_"

    public const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:_"

    public const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:_"

    public const val espresso_core: String = "androidx.test.espresso:espresso-core:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val junit_ktx: String = "androidx.test.ext:junit-ktx:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val lint_gradle: String = "com.android.tools.lint:lint-gradle:_"

    public const val material: String = "com.google.android.material:material:_"

    public const val hilt_android: String = "com.google.dagger:hilt-android:_"

    public const val hilt_android_compiler: String = "com.google.dagger:hilt-android-compiler:_"

    public const val hilt_android_gradle_plugin: String =
            "com.google.dagger:hilt-android-gradle-plugin:_"

    public const val hilt_android_testing: String = "com.google.dagger:hilt-android-testing:_"

    public const val hilt_compiler: String = "com.google.dagger:hilt-compiler:_"

    public const val timber: String = "com.jakewharton.timber:timber:_"

    public const val retrofit: String = "com.squareup.retrofit2:retrofit:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val kotest_assertions_core: String = "io.kotest:kotest-assertions-core:_"

    public const val mockk: String = "io.mockk:mockk:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:_"

    public const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    public const val kotlinx_coroutines_core_jvm: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:_"

    public const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    public const val robolectric: String = "org.robolectric:robolectric:_"
}
